# -*- coding: utf-8 -*-
"""Analyzing COVID-19 Data in Malaysia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGz3Rf2joCLxjQ-S6oG3oPzKuDCMR91Q
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://covid.ourworldindata.org/data/owid-covid-data.csv"
df = pd.read_csv(url)

df.head()

#filter for Malaysia data
malaysia_df = df[df['location'] == 'Malaysia']

malaysia_df[['date', 'new_cases', 'new_deaths', 'people_vaccinated', 'people_fully_vaccinated']].head()

#coverting date to datetime for plotting
malaysia_df['date'] = pd.to_datetime(malaysia_df['date'])

#Plot daily cases
plt.figure(figsize=(10, 6))
plt.plot(malaysia_df['date'], malaysia_df['new_cases'], label='Daily Cases', color = 'red')
plt.title('Daily new COVID-19 Cases in Malaysia')
plt.xlabel('Date')
plt.ylabel('Number of Cases')
plt.legend()
plt.grid(True)
plt.show()

#7-day moving average
malaysia_df['new_cases_7day_avg'] = malaysia_df['new_cases'].rolling(window=7).mean()

#Plotting
plt.figure(figsize=(12,6))
plt.plot(malaysia_df['date'], malaysia_df['new_cases'], label='Daily Cases', color='red')
plt.plot(malaysia_df['date'], malaysia_df['new_cases_7day_avg'], label='7-Day Moving Average', color='yellow')
plt.title('COVID-19 Daily Cases with 7-Day Average in Malaysia')
plt.xlabel('Date')
plt.ylabel('Number of Cases')
plt.legend()
plt.grid(True)
plt.show()

#PLotting daily new deaths
plt.figure(figsize=(12,6))
plt.plot(malaysia_df['date'], malaysia_df['new_deaths'], label='Daily Deaths', color='red')
plt.title('COVID-19 Daily Deaths in Malaysia')
plt.xlabel('Date')
plt.ylabel('Number of Deaths')
plt.legend()
plt.tight_layout()
plt.show()

#Vaccination Progress
plt.figure(figsize=(12,6))
plt.plot(malaysia_df['date'], malaysia_df['people_vaccinated'], label='People Vaccinated', color='orange')
plt.plot(malaysia_df['date'], malaysia_df['people_fully_vaccinated'], label='People Fully Vaccinated', color='red')
plt.title('COVID-19 Vaccination Progress in Malaysia')
plt.xlabel('Date')
plt.ylabel('Number of Vaccinations')
plt.legend()
plt.tight_layout()
plt.show()

"""- Daily cases peaked around August 2021, then it started declining
- Vaccination accelerated significantly from mid-2021
- There is a lag between peaks in cases and deaths
- The 7-day avg smooths out unneccesary fluctuations
"""